server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:demodb
    driverClassName: org.h2.Driver
    username: root
    password: pass
    hikari:
      pool-name: my-db-pool
      maximum-pool-size: 2
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false

logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    org.hibernate: OFF
    liquibase: INFO
    org.springframework.web: INFO